// <auto-generated />
using System;
using MarketAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketAgent.Infrastructure.Migrations
{
    [DbContext(typeof(MarketAgentDbContext))]
    [Migration("20260520193748_AddAlertEvents")]
    partial class AddAlertEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedAlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceAtSignal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ReasonJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SignalSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_AlertEvents_CreatedAtUtc");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_AlertEvents_Symbol");

                    b.HasIndex("SignalSnapshotId", "AlertType")
                        .IsUnique()
                        .HasDatabaseName("IX_AlertEvents_SignalSnapshotId_AlertType");

                    b.ToTable("AlertEvents", (string)null);
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedMarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("HighPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("LowPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("OpenPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PreviousClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("IX_MarketSnapshots_CapturedAtUtc");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_MarketSnapshots_Symbol");

                    b.HasIndex("Symbol", "CapturedAtUtc")
                        .HasDatabaseName("IX_MarketSnapshots_Symbol_CapturedAtUtc");

                    b.HasIndex("Symbol", "Source", "CapturedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_MarketSnapshots_Symbol_Source_CapturedAtUtc");

                    b.ToTable("MarketSnapshots", (string)null);
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedSignalOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDrawdownPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("MaxRunupPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("OutcomePercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PriceAfter15Minutes")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PriceAfter1Day")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PriceAfter1Hour")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PriceAfter4Hours")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PriceAtSignal")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("SignalSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAtUtc")
                        .HasDatabaseName("IX_SignalOutcomes_EvaluatedAtUtc");

                    b.HasIndex("EvaluationStatus")
                        .HasDatabaseName("IX_SignalOutcomes_EvaluationStatus");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("IX_SignalOutcomes_IsSuccessful");

                    b.HasIndex("SignalSnapshotId")
                        .IsUnique()
                        .HasDatabaseName("IX_SignalOutcomes_SignalSnapshotId");

                    b.ToTable("SignalOutcomes", (string)null);
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedSignalSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Ema20")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Ema50")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Ema9")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Entry")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ExtensionFromEma20Percent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("MarketRegime")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("OpenGapPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("OpeningRedReversalDetected")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RecoveryFromLowPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("RelativeStrengthVsSpy")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("RelativeVolume")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("Rsi")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SignalType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("Stop")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("Target")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TriggeredAlertsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_SignalSnapshots_CreatedAtUtc");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_SignalSnapshots_RunId");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_SignalSnapshots_Symbol");

                    b.HasIndex("Symbol", "CreatedAtUtc")
                        .HasDatabaseName("IX_SignalSnapshots_Symbol_CreatedAtUtc");

                    b.ToTable("SignalSnapshots", (string)null);
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedAlertEvent", b =>
                {
                    b.HasOne("MarketAgent.Infrastructure.Persistence.PersistedSignalSnapshot", "SignalSnapshot")
                        .WithMany("AlertEvents")
                        .HasForeignKey("SignalSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalSnapshot");
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedSignalOutcome", b =>
                {
                    b.HasOne("MarketAgent.Infrastructure.Persistence.PersistedSignalSnapshot", "SignalSnapshot")
                        .WithOne("Outcome")
                        .HasForeignKey("MarketAgent.Infrastructure.Persistence.PersistedSignalOutcome", "SignalSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalSnapshot");
                });

            modelBuilder.Entity("MarketAgent.Infrastructure.Persistence.PersistedSignalSnapshot", b =>
                {
                    b.Navigation("AlertEvents");

                    b.Navigation("Outcome");
                });
#pragma warning restore 612, 618
        }
    }
}
